PythonProject/PythonProject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.views.static import serve #需要导入
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^media/(?P<path>.*)$', serve, {'document_root':settings.MEDIA_ROOT}),#这部分很重要
    url(r'^ProductClass/', include('apps.ProductClass.urls', namespace='ProductClass')),  # 商品类别模块
    url(r'^ProductInfo/', include('apps.ProductInfo.urls', namespace='ProductInfo')),  # 产品信息模块
    url(r'^Supplyer/', include('apps.Supplyer.urls', namespace='Supplyer')),  # 供应商模块
    url(r'^CustomerInfo/', include('apps.CustomerInfo.urls', namespace='CustomerInfo')),  # 客户信息模块
    url(r'^BuyInfo/', include('apps.BuyInfo.urls', namespace='BuyInfo')),  # 产品进货模块
    url(r'^SellInfo/', include('apps.SellInfo.urls', namespace='SellInfo')),  # 产品销售模块

    url(r'^', include("apps.Index.urls", namespace="Index")),  # 首页模块

    url(r'^tinymce/', include('tinymce.urls')),
]

PythonProject/apps/CustomerInfo/urls.py
from apps.CustomerInfo.views import FrontAddView, FrontListView, UpdateView, DeletesView, FrontShowView, AddView, \
    ListView, OutToExcelView, BackModifyView, FrontModifyView, ListAllView
from django.conf.urls import url

# 正在部署的应用的名称
app_name = 'CustomerInfo'

urlpatterns = [
    url(r'^frontAdd$', FrontAddView.as_view(), name='frontAdd'),  # 前台添加
    url(r'^frontModify/(?P<customerId>.+)$', FrontModifyView.as_view(), name='frontModify'),  # 前台更新
    url(r'^frontList$', FrontListView.as_view(), name='frontList'),  # 前台查询列表
    url(r'^frontShow/(?P<customerId>.+)$', FrontShowView.as_view(), name='frontShow'),  # 前台显示详情页
    url(r'^listAll', ListAllView.as_view(), name='listAll'),  # 前台查询所有信息

    url(r'^update/(?P<customerId>.+)$', UpdateView.as_view(), name='update'),  # Ajax方式更新记录

    url(r'^add$', AddView.as_view(), name='add'),  # 后台添加
    url(r'^backModify/(?P<customerId>.+)$', BackModifyView.as_view(), name="backModify"),  # 后台更新
    url(r'^list$', ListView.as_view(), name='list'),  # 后台信息列表
    url(r'^deletes$', DeletesView.as_view(), name="deletes"),  # 删除记录信息
    url(r'^OutToExcel$', OutToExcelView.as_view(), name='OutToExcel')  # 导出信息到excel并下载
]

PythonProject/apps/Index/urls.py
from django.conf.urls import url
from apps.Index.views import IndexView,FrontLoginView,FrontLoginOutView,LoginView,LoginOutView,MainView,ChangePasswordView

# 正在部署的应用的名称
app_name = 'Index'

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),  # 首页
    url(r'^frontLogin$', FrontLoginView.as_view(), name='frontLogin'),  # 前台登录
    url(r'^frontLoginout$', FrontLoginOutView.as_view(), name='frontLoginout'),  # 前台退出
    url(r'^login$', LoginView.as_view(), name="login"),  # 后台登录
    url(r'^loginout$', LoginOutView.as_view(), name="loginout"),  # 后台退出
    url(r'^main$', MainView.as_view(), name='main'),  # 后台主页面
    url(r'^changePassword$', ChangePasswordView.as_view(), name='changePassword')  # 管理员修改密码
]

PythonProject/apps/CustomerInfo/models.py
from django.db import models


class CustomerInfo(models.Model):
    customerId = models.AutoField(primary_key=True, verbose_name='客户编号')
    customerName = models.CharField(max_length=20, default='', verbose_name='客户名称')
    personName = models.CharField(max_length=20, default='', verbose_name='联系人')
    telephone = models.CharField(max_length=20, default='', verbose_name='联系电话')
    address = models.CharField(max_length=20, default='', verbose_name='联系地址')

    class Meta:
        db_table = 't_CustomerInfo'
        verbose_name = '客户信息信息'
        verbose_name_plural = verbose_name

    def getJsonObj(self):
        customerInfo = {
            'customerId': self.customerId,
            'customerName': self.customerName,
            'personName': self.personName,
            'telephone': self.telephone,
            'address': self.address,
        }
        return customerInfo

PythonProject/apps/CustomerInfo/views.py
from django.views.generic import View
from apps.BaseView import BaseView
from django.shortcuts import render
from django.core.paginator import Paginator
from apps.CustomerInfo.models import CustomerInfo
from django.http import JsonResponse
from django.http import FileResponse
from apps.BaseView import ImageFormatException
from django.conf import settings
import pandas as pd
import os


class FrontAddView(BaseView):  # 前台客户信息添加
    def get(self,request):

        # 使用模板
        return render(request, 'CustomerInfo/customerInfo_frontAdd.html')

    def post(self, request):
        customerInfo = CustomerInfo() # 新建一个客户信息对象然后获取参数
        customerInfo.customerName = request.POST.get('customerInfo.customerName')
        customerInfo.personName = request.POST.get('customerInfo.personName')
        customerInfo.telephone = request.POST.get('customerInfo.telephone')
        customerInfo.address = request.POST.get('customerInfo.address')
        customerInfo.save() # 保存客户信息信息到数据库
        return JsonResponse({'success': True, 'message': '保存成功'})


class FrontModifyView(BaseView):  # 前台修改客户信息
    def get(self, request, customerId):
        context = {'customerId': customerId}
        return render(request, 'CustomerInfo/customerInfo_frontModify.html', context)


class FrontListView(BaseView):  # 前台客户信息查询列表
    def get(self, request):
        return self.handle(request)

    def post(self, request):
        return self.handle(request)

    def handle(self, request):
        self.getCurrentPage(request)  # 获取当前要显示第几页
        # 下面获取查询参数
        customerName = self.getStrParam(request, 'customerName')
        personName = self.getStrParam(request, 'personName')
        telephone = self.getStrParam(request, 'telephone')
        # 然后条件组合查询过滤
        customerInfos = CustomerInfo.objects.all()
        if customerName != '':
            customerInfos = customerInfos.filter(customerName__contains=customerName)
        if personName != '':
            customerInfos = customerInfos.filter(personName__contains=personName)
        if telephone != '':
            customerInfos = customerInfos.filter(telephone__contains=telephone)
        # 对查询结果利用Paginator进行分页
        self.paginator = Paginator(customerInfos, self.pageSize)
        # 计算总的页码数，要显示的页码列表，总记录等
        self.calculatePages()
        # 获取第page页的Page实例对象
        customerInfos_page = self.paginator.page(self.currentPage)

        # 构造模板需要的参数
        context = {
            'customerInfos_page': customerInfos_page,
            'customerName': customerName,
            'personName': personName,
            'telephone': telephone,
            'currentPage': self.currentPage,
            'totalPage': self.totalPage,
            'recordNumber': self.recordNumber,
            'startIndex': self.startIndex,
            'pageList': self.pageList,
        }
        # 渲染模板界面
        return render(request, 'CustomerInfo/customerInfo_frontquery_result.html', context)


class FrontShowView(View):  # 前台显示客户信息详情页
    def get(self, request, customerId):
        # 查询需要显示的客户信息对象
        customerInfo = CustomerInfo.objects.get(customerId=customerId)
        context = {
            'customerInfo': customerInfo
        }
        # 渲染模板显示
        return render(request, 'CustomerInfo/customerInfo_frontshow.html', context)


class ListAllView(View): # 前台查询所有客户信息
    def get(self,request):
        customerInfos = CustomerInfo.objects.all()
        customerInfoList = []
        for customerInfo in customerInfos:
            customerInfoObj = {
                'customerId': customerInfo.customerId,
                'customerName': customerInfo.customerName,
            }
            customerInfoList.append(customerInfoObj)
        return JsonResponse(customerInfoList, safe=False)


class UpdateView(BaseView):  # Ajax方式客户信息更新
    def get(self, request, customerId):
        # GET方式请求查询客户信息对象并返回客户信息json格式
        customerInfo = CustomerInfo.objects.get(customerId=customerId)
        return JsonResponse(customerInfo.getJsonObj())

    def post(self, request, customerId):
        # POST方式提交客户信息修改信息更新到数据库
        customerInfo = CustomerInfo.objects.get(customerId=customerId)
        customerInfo.customerName = request.POST.get('customerInfo.customerName')
        customerInfo.personName = request.POST.get('customerInfo.personName')
        customerInfo.telephone = request.POST.get('customerInfo.telephone')
        customerInfo.address = request.POST.get('customerInfo.address')
        customerInfo.save()
        return JsonResponse({'success': True, 'message': '保存成功'})

class AddView(BaseView):  # 后台客户信息添加
    def get(self,request):

        # 渲染显示模板界面
        return render(request, 'CustomerInfo/customerInfo_add.html')

    def post(self, request):
        # POST方式处理图书添加业务
        customerInfo = CustomerInfo() # 新建一个客户信息对象然后获取参数
        customerInfo.customerName = request.POST.get('customerInfo.customerName')
        customerInfo.personName = request.POST.get('customerInfo.personName')
        customerInfo.telephone = request.POST.get('customerInfo.telephone')
        customerInfo.address = request.POST.get('customerInfo.address')
        customerInfo.save() # 保存客户信息信息到数据库
        return JsonResponse({'success': True, 'message': '保存成功'})


class BackModifyView(BaseView):  # 后台更新客户信息
    def get(self, request, customerId):
        context = {'customerId': customerId}
        return render(request, 'CustomerInfo/customerInfo_modify.html', context)


class ListView(BaseView):  # 后台客户信息列表
    def get(self, request):
        # 使用模板
        return render(request, 'CustomerInfo/customerInfo_query_result.html')

    def post(self, request):
        # 获取当前要显示第几页和每页几条数据
        self.getPageAndSize(request)
        # 收集查询参数
        customerName = self.getStrParam(request, 'customerName')
        personName = self.getStrParam(request, 'personName')
        telephone = self.getStrParam(request, 'telephone')
        # 然后条件组合查询过滤
        customerInfos = CustomerInfo.objects.all()
        if customerName != '':
            customerInfos = customerInfos.filter(customerName__contains=customerName)
        if personName != '':
            customerInfos = customerInfos.filter(personName__contains=personName)
        if telephone != '':
            customerInfos = customerInfos.filter(telephone__contains=telephone)
        # 利用Paginator对查询结果集分页
        self.paginator = Paginator(customerInfos, self.pageSize)
        # 计算总的页码数，要显示的页码列表，总记录等
        self.calculatePages()
        # 获取第page页的Page实例对象
        customerInfos_page = self.paginator.page(self.currentPage)
        # 查询的结果集转换为列表
        customerInfoList = []
        for customerInfo in customerInfos_page:
            customerInfo = customerInfo.getJsonObj()
            customerInfoList.append(customerInfo)
        # 构造模板页面需要的参数
        customerInfo_res = {
            'rows': customerInfoList,
            'total': self.recordNumber,
        }
        # 渲染模板页面显示
        return JsonResponse(customerInfo_res, json_dumps_params={'ensure_ascii':False})

class DeletesView(BaseView):  # 删除客户信息信息
    def get(self, request):
        return self.handle(request)

    def post(self, request):
        return self.handle(request)

    def handle(self, request):
        customerIds = self.getStrParam(request, 'customerIds')
        customerIds = customerIds.split(',')
        count = 0
        try:
            for customerId in customerIds:
                CustomerInfo.objects.get(customerId=customerId).delete()
                count = count + 1
            message = '%s条记录删除成功！' % count
            success = True
        except Exception as e:
            message = '数据库外键约束删除失败！'
            success = False
        return JsonResponse({'success': success, 'message': message})


class OutToExcelView(BaseView):  # 导出客户信息信息到excel并下载
    def get(self, request):
        # 收集查询参数
        customerName = self.getStrParam(request, 'customerName')
        personName = self.getStrParam(request, 'personName')
        telephone = self.getStrParam(request, 'telephone')
        # 然后条件组合查询过滤
        customerInfos = CustomerInfo.objects.all()
        if customerName != '':
            customerInfos = customerInfos.filter(customerName__contains=customerName)
        if personName != '':
            customerInfos = customerInfos.filter(personName__contains=personName)
        if telephone != '':
            customerInfos = customerInfos.filter(telephone__contains=telephone)
        #将查询结果集转换成列表
        customerInfoList = []
        for customerInfo in customerInfos:
            customerInfo = customerInfo.getJsonObj()
            customerInfoList.append(customerInfo)
        # 利用pandas实现数据的导出功能
        pf = pd.DataFrame(customerInfoList)
        # 设置要导入到excel的列
        columns_map = {
            'customerId': '客户编号',
            'customerName': '客户名称',
            'personName': '联系人',
            'telephone': '联系电话',
            'address': '联系地址',
        }
        pf = pf[columns_map.keys()]
        pf.rename(columns=columns_map, inplace=True)
        # 将空的单元格替换为空字符
        pf.fillna('', inplace=True)
        #设定文件名和导出路径
        filename = 'customerInfos.xlsx'
        # 这个路径可以在settings中设置也可以直接手动输入
        root_path = settings.MEDIA_ROOT + '/output/'
        file_path = os.path.join(root_path, filename)
        pf.to_excel(file_path, encoding='utf-8', index=False)
        # 将生成的excel文件输出到网页下载
        file = open(file_path, 'rb')
        response = FileResponse(file)
        response['Content-Type'] = 'application/octet-stream'
        response['Content-Disposition'] = 'attachment;filename="customerInfos.xlsx"'
        return response

PythonProject/templates/CustomerInfo/customerInfo_frontquery_result.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
<title>客户信息查询</title>
<link href="{% static 'plugins/bootstrap.css' %}" rel="stylesheet">
<link href="{% static 'plugins/bootstrap-dashen.css' %}" rel="stylesheet">
<link href="{% static 'plugins/font-awesome.css' %}" rel="stylesheet">
<link href="{% static 'plugins/animate.css' %}" rel="stylesheet">
<link href="{% static 'plugins/bootstrap-datetimepicker.min.css' %}" rel="stylesheet" media="screen">
</head>
<body style="margin-top:70px;">
<div class="container">
{% include 'header.html' %}
	<div class="row"> 
	<div class="col-md-3 wow fadeInLeft">
		<div class="page-header">
    		<h1>客户信息查询</h1>
		</div>
		<form name="customerInfoQueryForm" id="customerInfoQueryForm" action="{% url 'CustomerInfo:frontList' %}" class="mar_t15" method="post">
			 {% csrf_token %}
			<div class="form-group">
				<label for="customerName">客户名称:</label>
				<input type="text" id="customerName" name="customerName" value="{{ customerName }}" class="form-control" placeholder="请输入客户名称">
			</div>
			<div class="form-group">
				<label for="personName">联系人:</label>
				<input type="text" id="personName" name="personName" value="{{ personName }}" class="form-control" placeholder="请输入联系人">
			</div>
			<div class="form-group">
				<label for="telephone">联系电话:</label>
				<input type="text" id="telephone" name="telephone" value="{{ telephone }}" class="form-control" placeholder="请输入联系电话">
			</div>
            <input type=hidden name=currentPage value="{{ currentPage }}" />
            <button type="submit" class="btn btn-primary">查询</button>
        </form>
	</div>

		<div class="col-md-9 wow fadeInDown" data-wow-duration="0.5s">
			<div>
				<!-- Nav tabs -->
				<ul class="nav nav-tabs" role="tablist">
			    	<li><a href="{% url 'Index:index' %}">首页</a></li>
			    	<li role="presentation" class="active"><a href="#customerInfoListPanel" aria-controls="customerInfoListPanel" role="tab" data-toggle="tab">客户信息列表</a></li>
			    	<li role="presentation" ><a href="{% url 'CustomerInfo:frontAdd' %}" style="display:none;">添加客户信息</a></li>
				</ul>
			  	<!-- Tab panes -->
			  	<div class="tab-content">
				    <div role="tabpanel" class="tab-pane active" id="customerInfoListPanel">
				    		<div class="row">
				    			<div class="col-md-12 top5">
				    				<div class="table-responsive">
				    				<table class="table table-condensed table-hover">
				    					<tr class="success bold"><td>序号</td><td>客户编号</td><td>客户名称</td><td>联系人</td><td>联系电话</td><td>联系地址</td><td>操作</td></tr>
                                        {% for customerInfo in customerInfos_page %}
 										<tr>
 											<td>{{ startIndex|add:forloop.counter }}</td>
 											<td>{{ customerInfo.customerId }}</td>
 											<td>{{ customerInfo.customerName }}</td>
 											<td>{{ customerInfo.personName }}</td>
 											<td>{{ customerInfo.telephone }}</td>
 											<td>{{ customerInfo.address }}</td>
 											<td>
 												<a href="{% url 'CustomerInfo:frontShow' customerInfo.customerId  %}"><i class="fa fa-info"></i>&nbsp;查看</a>&nbsp;
 												<a href="#" onclick="customerInfoEdit('{{ customerInfo.customerId }}');" style="display:none;"><i class="fa fa-pencil fa-fw"></i>编辑</a>&nbsp;
 												<a href="#" onclick="customerInfoDelete('{{ customerInfo.customerId }}');" style="display:none;"><i class="fa fa-trash-o fa-fw"></i>删除</a>
 											</td> 
 										</tr>
 										{% endfor %}
				    				</table>
				    				</div>
				    			</div>
				    		</div>

				    		<div class="row">
					            <div class="col-md-12">
						            <nav class="pull-left">
						                <ul class="pagination">
						                    <li><a href="#" onclick="GoToPage({{ currentPage|add:-1 }},{{ totalPage }}>);" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a></li>
                                            {% for page in pageList %}
                                            {% if currentPage == page %}
						                        <li class="active"><a href="#"  onclick="GoToPage({{ page }},{{ totalPage }});">{{ page }}</a></li>
						                    {% else %}
                                                <li><a href="#"  onclick="GoToPage({{ page }},{{ totalPage }});">{{ page }}</a></li>
                                            {% endif %}
                                            {% endfor %}
						                    <li><a href="#" onclick="GoToPage({{ currentPage|add:1 }},{{ totalPage }});"><span aria-hidden="true">&raquo;</span></a></li>
						                </ul>
						            </nav>
						            <div class="pull-right" style="line-height:75px;" >共有{{ recordNumber }}条记录，当前第{{ currentPage }}/{{ totalPage }} 页</div>
					            </div>
				            </div> 
				    </div>
				</div>
			</div>
		</div>
		</div>
	</div> 
<div id="customerInfoEditDialog" class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title"><i class="fa fa-edit"></i>&nbsp;客户信息信息编辑</h4>
      </div>
      <div class="modal-body" style="height:450px; overflow: scroll;">
      	<form class="form-horizontal" name="customerInfoEditForm" id="customerInfoEditForm" enctype="multipart/form-data" method="post"  class="mar_t15">
		    {% csrf_token %}
		  <div class="form-group">
			 <label for="customerInfo_customerId_edit" class="col-md-3 text-right">客户编号:</label>
			 <div class="col-md-9"> 
			 	<input type="text" id="customerInfo_customerId_edit" name="customerInfo.customerId" class="form-control" placeholder="请输入客户编号" readOnly>
			 </div>
		  </div> 
		  <div class="form-group">
		  	 <label for="customerInfo_customerName_edit" class="col-md-3 text-right">客户名称:</label>
		  	 <div class="col-md-9">
			    <input type="text" id="customerInfo_customerName_edit" name="customerInfo.customerName" class="form-control" placeholder="请输入客户名称">
			 </div>
		  </div>
		  <div class="form-group">
		  	 <label for="customerInfo_personName_edit" class="col-md-3 text-right">联系人:</label>
		  	 <div class="col-md-9">
			    <input type="text" id="customerInfo_personName_edit" name="customerInfo.personName" class="form-control" placeholder="请输入联系人">
			 </div>
		  </div>
		  <div class="form-group">
		  	 <label for="customerInfo_telephone_edit" class="col-md-3 text-right">联系电话:</label>
		  	 <div class="col-md-9">
			    <input type="text" id="customerInfo_telephone_edit" name="customerInfo.telephone" class="form-control" placeholder="请输入联系电话">
			 </div>
		  </div>
		  <div class="form-group">
		  	 <label for="customerInfo_address_edit" class="col-md-3 text-right">联系地址:</label>
		  	 <div class="col-md-9">
			    <input type="text" id="customerInfo_address_edit" name="customerInfo.address" class="form-control" placeholder="请输入联系地址">
			 </div>
		  </div>
		</form> 
	    <style>#customerInfoEditForm .form-group {margin-bottom:5px;}  </style>
      </div>
      <div class="modal-footer"> 
      	<button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
      	<button type="button" class="btn btn-primary" onclick="ajaxCustomerInfoModify();">提交</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
{% include 'footer.html' %}
<script src="{% static 'plugins/jquery.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap.js' %}"></script>
<script src="{% static 'plugins/wow.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap-datetimepicker.min.js' %}"></script>
<script src="{% static 'plugins/locales/bootstrap-datetimepicker.zh-CN.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jsdate.js' %}"></script>
<script>
/*跳转到查询结果的某页*/
function GoToPage(currentPage,totalPage) {
    if(currentPage==0) return;
    if(currentPage>totalPage) return;
    document.customerInfoQueryForm.currentPage.value = currentPage;
    document.customerInfoQueryForm.submit();
}

/*可以直接跳转到某页*/
function changepage(totalPage)
{
    var pageValue=document.customerInfoQueryForm.pageValue.value;
    if(pageValue>totalPage) {
        alert('你输入的页码超出了总页数!');
        return ;
    }
    document.customerInfoQueryForm.currentPage.value = pageValue;
    documentcustomerInfoQueryForm.submit();
}

/*弹出修改客户信息界面并初始化数据*/
function customerInfoEdit(customerId) {
	$.ajax({
		url :  '/CustomerInfo/update/' + customerId,
		type : "get",
		dataType: "json",
		success : function (customerInfo, response, status) {
			if (customerInfo) {
				$("#customerInfo_customerId_edit").val(customerInfo.customerId);
				$("#customerInfo_customerName_edit").val(customerInfo.customerName);
				$("#customerInfo_personName_edit").val(customerInfo.personName);
				$("#customerInfo_telephone_edit").val(customerInfo.telephone);
				$("#customerInfo_address_edit").val(customerInfo.address);
				$('#customerInfoEditDialog').modal('show');
			} else {
				alert("获取信息失败！");
			}
		}
	});
}

/*删除客户信息信息*/
function customerInfoDelete(customerId) {
    var csrf = $('input[name="csrfmiddlewaretoken"]').val();
	if(confirm("确认删除这个记录")) {
		$.ajax({
			type : "POST",
			url : "/CustomerInfo/deletes",
			data : {
				customerIds : customerId,
                "csrfmiddlewaretoken": csrf
			},
			success : function (obj) {
				if (obj.success) {
					alert("删除成功");
					$("#customerInfoQueryForm").submit();
					//location.href= basePath + "CustomerInfo/frontlist";
				}
				else 
					alert(obj.message);
			},
		});
	}
}

/*ajax方式提交客户信息信息表单给服务器端修改*/
function ajaxCustomerInfoModify() {
	$.ajax({
		url :   '/CustomerInfo/update/' + $("#customerInfo_customerId_edit").val(),
		type : "post",
		dataType: "json",
		data: new FormData($("#customerInfoEditForm")[0]),
		success : function (obj, response, status) {
            if(obj.success){
                alert("信息修改成功！");
                $("#customerInfoQueryForm").submit();
            }else{
                alert(obj.message);
            } 
		},
		processData: false,
		contentType: false,
	});
}

$(function(){
	/*小屏幕导航点击关闭菜单*/
    $('.navbar-collapse a').click(function(){
        $('.navbar-collapse').collapse('hide');
    });
    new WOW().init();

})
</script>
</body>
</html>

PythonProject/templates/CustomerInfo/customerInfo_frontshow.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
  <TITLE>查看客户信息详情</TITLE>
  <link href="{% static 'plugins/bootstrap.css' %}" rel="stylesheet">
  <link href="{% static 'plugins/bootstrap-dashen.css' %}" rel="stylesheet">
  <link href="{% static 'plugins/font-awesome.css' %}" rel="stylesheet">
  <link href="{% static 'plugins/animate.css' %}" rel="stylesheet">
</head>
<body style="margin-top:70px;"> 
{% include 'header.html' %}
<div class="container">
	<ul class="breadcrumb">
  		<li><a href={% url 'Index:index' %}">首页</a></li>
  		<li><a href="{% url 'CustomerInfo:frontList' %}">客户信息信息</a></li>
  		<li class="active">详情查看</li>
	</ul>
	<div class="row bottom15"> 
		<div class="col-md-2 col-xs-4 text-right bold">客户编号:</div>
		<div class="col-md-10 col-xs-6">{{ customerInfo.customerId }}</div>
	</div>
	<div class="row bottom15"> 
		<div class="col-md-2 col-xs-4 text-right bold">客户名称:</div>
		<div class="col-md-10 col-xs-6">{{ customerInfo.customerName }}</div>
	</div>
	<div class="row bottom15"> 
		<div class="col-md-2 col-xs-4 text-right bold">联系人:</div>
		<div class="col-md-10 col-xs-6">{{ customerInfo.personName }}</div>
	</div>
	<div class="row bottom15"> 
		<div class="col-md-2 col-xs-4 text-right bold">联系电话:</div>
		<div class="col-md-10 col-xs-6">{{ customerInfo.telephone }}</div>
	</div>
	<div class="row bottom15"> 
		<div class="col-md-2 col-xs-4 text-right bold">联系地址:</div>
		<div class="col-md-10 col-xs-6">{{ customerInfo.address }}</div>
	</div>
	<div class="row bottom15">
		<div class="col-md-2 col-xs-4"></div>
		<div class="col-md-6 col-xs-6">
			<button onclick="history.back();" class="btn btn-primary">返回</button>
		</div>
	</div>
</div> 
{% include 'footer.html' %}
<script src="{% static 'plugins/jquery.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap.js' %}"></script>
<script src="{% static 'plugins/wow.min.js' %}"></script>
<script>
$(function(){
        /*小屏幕导航点击关闭菜单*/
        $('.navbar-collapse a').click(function(){
            $('.navbar-collapse').collapse('hide');
        });
        new WOW().init();
 })
 </script> 
</body>
</html>