PythonProject/PythonProject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.views.static import serve #需要导入
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^media/(?P<path>.*)$', serve, {'document_root':settings.MEDIA_ROOT}),#这部分很重要
    url(r'^ProductClass/', include('apps.ProductClass.urls', namespace='ProductClass')),  # 商品类别模块
    url(r'^ProductInfo/', include('apps.ProductInfo.urls', namespace='ProductInfo')),  # 产品信息模块
    url(r'^Supplyer/', include('apps.Supplyer.urls', namespace='Supplyer')),  # 供应商模块
    url(r'^CustomerInfo/', include('apps.CustomerInfo.urls', namespace='CustomerInfo')),  # 客户信息模块
    url(r'^BuyInfo/', include('apps.BuyInfo.urls', namespace='BuyInfo')),  # 产品进货模块
    url(r'^SellInfo/', include('apps.SellInfo.urls', namespace='SellInfo')),  # 产品销售模块

    url(r'^', include("apps.Index.urls", namespace="Index")),  # 首页模块

    url(r'^tinymce/', include('tinymce.urls')),
]

PythonProject/apps/Index/urls.py
from django.conf.urls import url
from apps.Index.views import IndexView,FrontLoginView,FrontLoginOutView,LoginView,LoginOutView,MainView,ChangePasswordView

# 正在部署的应用的名称
app_name = 'Index'

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),  # 首页
    url(r'^frontLogin$', FrontLoginView.as_view(), name='frontLogin'),  # 前台登录
    url(r'^frontLoginout$', FrontLoginOutView.as_view(), name='frontLoginout'),  # 前台退出
    url(r'^login$', LoginView.as_view(), name="login"),  # 后台登录
    url(r'^loginout$', LoginOutView.as_view(), name="loginout"),  # 后台退出
    url(r'^main$', MainView.as_view(), name='main'),  # 后台主页面
    url(r'^changePassword$', ChangePasswordView.as_view(), name='changePassword')  # 管理员修改密码
]

PythonProject/apps/ProductClass/urls.py
from apps.ProductClass.views import FrontAddView, FrontListView, UpdateView, DeletesView, FrontShowView, AddView, \
    ListView, OutToExcelView, BackModifyView, FrontModifyView, ListAllView
from django.conf.urls import url

# 正在部署的应用的名称
app_name = 'ProductClass'

urlpatterns = [
    url(r'^frontAdd$', FrontAddView.as_view(), name='frontAdd'),  # 前台添加
    url(r'^frontModify/(?P<productClassId>.+)$', FrontModifyView.as_view(), name='frontModify'),  # 前台更新
    url(r'^frontList$', FrontListView.as_view(), name='frontList'),  # 前台查询列表
    url(r'^frontShow/(?P<productClassId>.+)$', FrontShowView.as_view(), name='frontShow'),  # 前台显示详情页
    url(r'^listAll', ListAllView.as_view(), name='listAll'),  # 前台查询所有信息

    url(r'^update/(?P<productClassId>.+)$', UpdateView.as_view(), name='update'),  # Ajax方式更新记录

    url(r'^add$', AddView.as_view(), name='add'),  # 后台添加
    url(r'^backModify/(?P<productClassId>.+)$', BackModifyView.as_view(), name="backModify"),  # 后台更新
    url(r'^list$', ListView.as_view(), name='list'),  # 后台信息列表
    url(r'^deletes$', DeletesView.as_view(), name="deletes"),  # 删除记录信息
    url(r'^OutToExcel$', OutToExcelView.as_view(), name='OutToExcel')  # 导出信息到excel并下载
]

PythonProject/apps/ProductClass/models.py
from django.db import models


class ProductClass(models.Model):
    productClassId = models.AutoField(primary_key=True, verbose_name='商品类别编号')
    productClassName = models.CharField(max_length=20, default='', verbose_name='商品类别名称')

    class Meta:
        db_table = 't_ProductClass'
        verbose_name = '商品类别信息'
        verbose_name_plural = verbose_name

    def getJsonObj(self):
        productClass = {
            'productClassId': self.productClassId,
            'productClassName': self.productClassName,
        }
        return productClass

PythonProject/apps/ProductClass/views.py
from django.views.generic import View
from apps.BaseView import BaseView
from django.shortcuts import render
from django.core.paginator import Paginator
from apps.ProductClass.models import ProductClass
from django.http import JsonResponse
from django.http import FileResponse
from apps.BaseView import ImageFormatException
from django.conf import settings
import pandas as pd
import os


class FrontAddView(BaseView):  # 前台商品类别添加
    def get(self,request):

        # 使用模板
        return render(request, 'ProductClass/productClass_frontAdd.html')

    def post(self, request):
        productClass = ProductClass() # 新建一个商品类别对象然后获取参数
        productClass.productClassName = request.POST.get('productClass.productClassName')
        productClass.save() # 保存商品类别信息到数据库
        return JsonResponse({'success': True, 'message': '保存成功'})


class FrontModifyView(BaseView):  # 前台修改商品类别
    def get(self, request, productClassId):
        context = {'productClassId': productClassId}
        return render(request, 'ProductClass/productClass_frontModify.html', context)


class FrontListView(BaseView):  # 前台商品类别查询列表
    def get(self, request):
        return self.handle(request)

    def post(self, request):
        return self.handle(request)

    def handle(self, request):
        self.getCurrentPage(request)  # 获取当前要显示第几页
        # 下面获取查询参数
        # 然后条件组合查询过滤
        productClasss = ProductClass.objects.all()
        # 对查询结果利用Paginator进行分页
        self.paginator = Paginator(productClasss, self.pageSize)
        # 计算总的页码数，要显示的页码列表，总记录等
        self.calculatePages()
        # 获取第page页的Page实例对象
        productClasss_page = self.paginator.page(self.currentPage)

        # 构造模板需要的参数
        context = {
            'productClasss_page': productClasss_page,
            'currentPage': self.currentPage,
            'totalPage': self.totalPage,
            'recordNumber': self.recordNumber,
            'startIndex': self.startIndex,
            'pageList': self.pageList,
        }
        # 渲染模板界面
        return render(request, 'ProductClass/productClass_frontquery_result.html', context)


class FrontShowView(View):  # 前台显示商品类别详情页
    def get(self, request, productClassId):
        # 查询需要显示的商品类别对象
        productClass = ProductClass.objects.get(productClassId=productClassId)
        context = {
            'productClass': productClass
        }
        # 渲染模板显示
        return render(request, 'ProductClass/productClass_frontshow.html', context)


class ListAllView(View): # 前台查询所有商品类别
    def get(self,request):
        productClasss = ProductClass.objects.all()
        productClassList = []
        for productClass in productClasss:
            productClassObj = {
                'productClassId': productClass.productClassId,
                'productClassName': productClass.productClassName,
            }
            productClassList.append(productClassObj)
        return JsonResponse(productClassList, safe=False)


class UpdateView(BaseView):  # Ajax方式商品类别更新
    def get(self, request, productClassId):
        # GET方式请求查询商品类别对象并返回商品类别json格式
        productClass = ProductClass.objects.get(productClassId=productClassId)
        return JsonResponse(productClass.getJsonObj())

    def post(self, request, productClassId):
        # POST方式提交商品类别修改信息更新到数据库
        productClass = ProductClass.objects.get(productClassId=productClassId)
        productClass.productClassName = request.POST.get('productClass.productClassName')
        productClass.save()
        return JsonResponse({'success': True, 'message': '保存成功'})

class AddView(BaseView):  # 后台商品类别添加
    def get(self,request):

        # 渲染显示模板界面
        return render(request, 'ProductClass/productClass_add.html')

    def post(self, request):
        # POST方式处理图书添加业务
        productClass = ProductClass() # 新建一个商品类别对象然后获取参数
        productClass.productClassName = request.POST.get('productClass.productClassName')
        productClass.save() # 保存商品类别信息到数据库
        return JsonResponse({'success': True, 'message': '保存成功'})


class BackModifyView(BaseView):  # 后台更新商品类别
    def get(self, request, productClassId):
        context = {'productClassId': productClassId}
        return render(request, 'ProductClass/productClass_modify.html', context)


class ListView(BaseView):  # 后台商品类别列表
    def get(self, request):
        # 使用模板
        return render(request, 'ProductClass/productClass_query_result.html')

    def post(self, request):
        # 获取当前要显示第几页和每页几条数据
        self.getPageAndSize(request)
        # 收集查询参数
        # 然后条件组合查询过滤
        productClasss = ProductClass.objects.all()
        # 利用Paginator对查询结果集分页
        self.paginator = Paginator(productClasss, self.pageSize)
        # 计算总的页码数，要显示的页码列表，总记录等
        self.calculatePages()
        # 获取第page页的Page实例对象
        productClasss_page = self.paginator.page(self.currentPage)
        # 查询的结果集转换为列表
        productClassList = []
        for productClass in productClasss_page:
            productClass = productClass.getJsonObj()
            productClassList.append(productClass)
        # 构造模板页面需要的参数
        productClass_res = {
            'rows': productClassList,
            'total': self.recordNumber,
        }
        # 渲染模板页面显示
        return JsonResponse(productClass_res, json_dumps_params={'ensure_ascii':False})

class DeletesView(BaseView):  # 删除商品类别信息
    def get(self, request):
        return self.handle(request)

    def post(self, request):
        return self.handle(request)

    def handle(self, request):
        productClassIds = self.getStrParam(request, 'productClassIds')
        productClassIds = productClassIds.split(',')
        count = 0
        try:
            for productClassId in productClassIds:
                ProductClass.objects.get(productClassId=productClassId).delete()
                count = count + 1
            message = '%s条记录删除成功！' % count
            success = True
        except Exception as e:
            message = '数据库外键约束删除失败！'
            success = False
        return JsonResponse({'success': success, 'message': message})


class OutToExcelView(BaseView):  # 导出商品类别信息到excel并下载
    def get(self, request):
        # 收集查询参数
        # 然后条件组合查询过滤
        productClasss = ProductClass.objects.all()
        #将查询结果集转换成列表
        productClassList = []
        for productClass in productClasss:
            productClass = productClass.getJsonObj()
            productClassList.append(productClass)
        # 利用pandas实现数据的导出功能
        pf = pd.DataFrame(productClassList)
        # 设置要导入到excel的列
        columns_map = {
            'productClassId': '商品类别编号',
            'productClassName': '商品类别名称',
        }
        pf = pf[columns_map.keys()]
        pf.rename(columns=columns_map, inplace=True)
        # 将空的单元格替换为空字符
        pf.fillna('', inplace=True)
        #设定文件名和导出路径
        filename = 'productClasss.xlsx'
        # 这个路径可以在settings中设置也可以直接手动输入
        root_path = settings.MEDIA_ROOT + '/output/'
        file_path = os.path.join(root_path, filename)
        pf.to_excel(file_path, encoding='utf-8', index=False)
        # 将生成的excel文件输出到网页下载
        file = open(file_path, 'rb')
        response = FileResponse(file)
        response['Content-Type'] = 'application/octet-stream'
        response['Content-Disposition'] = 'attachment;filename="productClasss.xlsx"'
        return response

PythonProject/templates/ProductClass/productClass_add.html
{% include 'check_logstate.html' %}
{% load staticfiles %}

 <link rel="stylesheet" type="text/css" href="{% static 'css/productClass.css' %}" />
<div id="productClassAddDiv">
    {% csrf_token %}
	<form id="productClassAddForm" enctype="multipart/form-data"  method="post">
		<div>
			<span class="label">商品类别名称:</span>
			<span class="inputControl">
				<input class="textbox" type="text" id="productClass_productClassName" name="productClass.productClassName" style="width:200px" />

			</span>

		</div>
		<div class="operation">
			<a id="productClassAddButton" class="easyui-linkbutton">添加</a>
			<a id="productClassClearButton" class="easyui-linkbutton">重填</a>
		</div> 
	</form>
</div>
<script src="{% static 'js/ProductClass/productClass_add.js' %}"></script>

PythonProject/templates/ProductClass/productClass_frontAdd.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
<title>商品类别添加</title>
<link href="{% static 'plugins/bootstrap.css' %}" rel="stylesheet">
<link href="{% static 'plugins/bootstrap-dashen.css' %}" rel="stylesheet">
<link href="{% static 'plugins/font-awesome.css' %}" rel="stylesheet">
<link href="{% static 'plugins/animate.css' %}" rel="stylesheet">
<link href="{% static 'plugins/bootstrap-datetimepicker.min.css' %}" rel="stylesheet" media="screen">
</head>
<body style="margin-top:70px;">
{% include 'header.html' %}
<div class="container">
	<div class="row">
		<div class="col-md-12 wow fadeInUp" data-wow-duration="0.5s">
			<div>
				<!-- Nav tabs -->
				<ul class="nav nav-tabs" role="tablist">
			    	<li role="presentation" ><a href="{% url 'ProductClass:frontList' %}">商品类别列表</a></li>
			    	<li role="presentation" class="active"><a href="#productClassAdd" aria-controls="productClassAdd" role="tab" data-toggle="tab">添加商品类别</a></li>
				</ul>
				<!-- Tab panes -->
				<div class="tab-content">
				    <div role="tabpanel" class="tab-pane" id="productClassList">
				    </div>
				    <div role="tabpanel" class="tab-pane active" id="productClassAdd"> 
				      	<form class="form-horizontal" name="productClassAddForm" id="productClassAddForm" enctype="multipart/form-data" method="post"  class="mar_t15">
				    {% csrf_token %}
						  <div class="form-group">
						  	 <label for="productClass_productClassName" class="col-md-2 text-right">商品类别名称:</label>
						  	 <div class="col-md-8">
							    <input type="text" id="productClass_productClassName" name="productClass.productClassName" class="form-control" placeholder="请输入商品类别名称">
							 </div>
						  </div>
				          <div class="form-group">
				             <span class="col-md-2""></span>
				             <span onclick="ajaxProductClassAdd();" class="btn btn-primary bottom5 top5">添加</span>
				          </div>
						</form> 
				        <style>#productClassAddForm .form-group {margin:10px;}  </style>
					</div>
				</div>
			</div>
		</div>
	</div> 
</div>

{% include 'footer.html' %}
<script src="{% static 'plugins/jquery.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap.js' %}"></script>
<script src="{% static 'plugins/wow.min.js' %}"></script>
<script src="{% static 'plugins/bootstrapvalidator/js/bootstrapValidator.min.js' %}"></script>
<script type="text/javascript" src="{% static 'plugins/bootstrap-datetimepicker.min.js' %}" charset="UTF-8"></script>
<script type="text/javascript" src="{% static 'plugins/locales/bootstrap-datetimepicker.zh-CN.js' %}" charset="UTF-8"></script>
<script>
	//提交添加商品类别信息
	function ajaxProductClassAdd() { 
		//提交之前先验证表单
		$("#productClassAddForm").data('bootstrapValidator').validate();
		if(!$("#productClassAddForm").data('bootstrapValidator').isValid()){
			return;
		}
		jQuery.ajax({
			type : "post",
			url : "{% url 'ProductClass:frontAdd' %}",
			dataType : "json" , 
			data: new FormData($("#productClassAddForm")[0]),
			success : function(obj) {
				if(obj.success){ 
					alert("保存成功！");
					location.reload();
				} else {
					alert(obj.message);
				}
			},
			processData: false, 
			contentType: false, 
		});
	} 
$(function(){
	/*小屏幕导航点击关闭菜单*/
    $('.navbar-collapse a').click(function(){
        $('.navbar-collapse').collapse('hide');
    });
    new WOW().init();
	//验证商品类别添加表单字段
	$('#productClassAddForm').bootstrapValidator({
		feedbackIcons: {
			valid: 'glyphicon glyphicon-ok',
			invalid: 'glyphicon glyphicon-remove',
			validating: 'glyphicon glyphicon-refresh'
		},
		fields: {
			"productClass.productClassName": {
				validators: {
					notEmpty: {
						message: "商品类别名称不能为空",
					}
				}
			},
		}
	}); 
})
</script>
</body>
</html>

PythonProject/templates/ProductClass/productClass_frontquery_result.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
<title>商品类别查询</title>
<link href="{% static 'plugins/bootstrap.css' %}" rel="stylesheet">
<link href="{% static 'plugins/bootstrap-dashen.css' %}" rel="stylesheet">
<link href="{% static 'plugins/font-awesome.css' %}" rel="stylesheet">
<link href="{% static 'plugins/animate.css' %}" rel="stylesheet">
<link href="{% static 'plugins/bootstrap-datetimepicker.min.css' %}" rel="stylesheet" media="screen">
</head>
<body style="margin-top:70px;">
<div class="container">
{% include 'header.html' %}
	<div class="row"> 
	<div style="display:none;">
		<div class="page-header">
    		<h1>商品类别查询</h1>
		</div>
		<form name="productClassQueryForm" id="productClassQueryForm" action="{% url 'ProductClass:frontList' %}" class="mar_t15" method="post">
			 {% csrf_token %}
            <input type=hidden name=currentPage value="{{ currentPage }}" />
            <button type="submit" class="btn btn-primary">查询</button>
        </form>
	</div>

		<div class="col-md-12 wow fadeInDown" data-wow-duration="0.5s">
			<div>
				<!-- Nav tabs -->
				<ul class="nav nav-tabs" role="tablist">
			    	<li><a href="{% url 'Index:index' %}">首页</a></li>
			    	<li role="presentation" class="active"><a href="#productClassListPanel" aria-controls="productClassListPanel" role="tab" data-toggle="tab">商品类别列表</a></li>
			    	<li role="presentation" ><a href="{% url 'ProductClass:frontAdd' %}" style="display:none;">添加商品类别</a></li>
				</ul>
			  	<!-- Tab panes -->
			  	<div class="tab-content">
				    <div role="tabpanel" class="tab-pane active" id="productClassListPanel">
				    		<div class="row">
				    			<div class="col-md-12 top5">
				    				<div class="table-responsive">
				    				<table class="table table-condensed table-hover">
				    					<tr class="success bold"><td>序号</td><td>商品类别编号</td><td>商品类别名称</td><td>操作</td></tr>
                                        {% for productClass in productClasss_page %}
 										<tr>
 											<td>{{ startIndex|add:forloop.counter }}</td>
 											<td>{{ productClass.productClassId }}</td>
 											<td>{{ productClass.productClassName }}</td>
 											<td>
 												<a href="{% url 'ProductClass:frontShow' productClass.productClassId  %}"><i class="fa fa-info"></i>&nbsp;查看</a>&nbsp;
 												<a href="#" onclick="productClassEdit('{{ productClass.productClassId }}');" style="display:none;"><i class="fa fa-pencil fa-fw"></i>编辑</a>&nbsp;
 												<a href="#" onclick="productClassDelete('{{ productClass.productClassId }}');" style="display:none;"><i class="fa fa-trash-o fa-fw"></i>删除</a>
 											</td> 
 										</tr>
 										{% endfor %}
				    				</table>
				    				</div>
				    			</div>
				    		</div>

				    		<div class="row">
					            <div class="col-md-12">
						            <nav class="pull-left">
						                <ul class="pagination">
						                    <li><a href="#" onclick="GoToPage({{ currentPage|add:-1 }},{{ totalPage }}>);" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a></li>
                                            {% for page in pageList %}
                                            {% if currentPage == page %}
						                        <li class="active"><a href="#"  onclick="GoToPage({{ page }},{{ totalPage }});">{{ page }}</a></li>
						                    {% else %}
                                                <li><a href="#"  onclick="GoToPage({{ page }},{{ totalPage }});">{{ page }}</a></li>
                                            {% endif %}
                                            {% endfor %}
						                    <li><a href="#" onclick="GoToPage({{ currentPage|add:1 }},{{ totalPage }});"><span aria-hidden="true">&raquo;</span></a></li>
						                </ul>
						            </nav>
						            <div class="pull-right" style="line-height:75px;" >共有{{ recordNumber }}条记录，当前第{{ currentPage }}/{{ totalPage }} 页</div>
					            </div>
				            </div> 
				    </div>
				</div>
			</div>
		</div>
		</div>
	</div> 
<div id="productClassEditDialog" class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title"><i class="fa fa-edit"></i>&nbsp;商品类别信息编辑</h4>
      </div>
      <div class="modal-body" style="height:450px; overflow: scroll;">
      	<form class="form-horizontal" name="productClassEditForm" id="productClassEditForm" enctype="multipart/form-data" method="post"  class="mar_t15">
		    {% csrf_token %}
		  <div class="form-group">
			 <label for="productClass_productClassId_edit" class="col-md-3 text-right">商品类别编号:</label>
			 <div class="col-md-9"> 
			 	<input type="text" id="productClass_productClassId_edit" name="productClass.productClassId" class="form-control" placeholder="请输入商品类别编号" readOnly>
			 </div>
		  </div> 
		  <div class="form-group">
		  	 <label for="productClass_productClassName_edit" class="col-md-3 text-right">商品类别名称:</label>
		  	 <div class="col-md-9">
			    <input type="text" id="productClass_productClassName_edit" name="productClass.productClassName" class="form-control" placeholder="请输入商品类别名称">
			 </div>
		  </div>
		</form> 
	    <style>#productClassEditForm .form-group {margin-bottom:5px;}  </style>
      </div>
      <div class="modal-footer"> 
      	<button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
      	<button type="button" class="btn btn-primary" onclick="ajaxProductClassModify();">提交</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
{% include 'footer.html' %}
<script src="{% static 'plugins/jquery.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap.js' %}"></script>
<script src="{% static 'plugins/wow.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap-datetimepicker.min.js' %}"></script>
<script src="{% static 'plugins/locales/bootstrap-datetimepicker.zh-CN.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jsdate.js' %}"></script>
<script>
/*跳转到查询结果的某页*/
function GoToPage(currentPage,totalPage) {
    if(currentPage==0) return;
    if(currentPage>totalPage) return;
    document.productClassQueryForm.currentPage.value = currentPage;
    document.productClassQueryForm.submit();
}

/*可以直接跳转到某页*/
function changepage(totalPage)
{
    var pageValue=document.productClassQueryForm.pageValue.value;
    if(pageValue>totalPage) {
        alert('你输入的页码超出了总页数!');
        return ;
    }
    document.productClassQueryForm.currentPage.value = pageValue;
    documentproductClassQueryForm.submit();
}

/*弹出修改商品类别界面并初始化数据*/
function productClassEdit(productClassId) {
	$.ajax({
		url :  '/ProductClass/update/' + productClassId,
		type : "get",
		dataType: "json",
		success : function (productClass, response, status) {
			if (productClass) {
				$("#productClass_productClassId_edit").val(productClass.productClassId);
				$("#productClass_productClassName_edit").val(productClass.productClassName);
				$('#productClassEditDialog').modal('show');
			} else {
				alert("获取信息失败！");
			}
		}
	});
}

/*删除商品类别信息*/
function productClassDelete(productClassId) {
    var csrf = $('input[name="csrfmiddlewaretoken"]').val();
	if(confirm("确认删除这个记录")) {
		$.ajax({
			type : "POST",
			url : "/ProductClass/deletes",
			data : {
				productClassIds : productClassId,
                "csrfmiddlewaretoken": csrf
			},
			success : function (obj) {
				if (obj.success) {
					alert("删除成功");
					$("#productClassQueryForm").submit();
					//location.href= basePath + "ProductClass/frontlist";
				}
				else 
					alert(obj.message);
			},
		});
	}
}

/*ajax方式提交商品类别信息表单给服务器端修改*/
function ajaxProductClassModify() {
	$.ajax({
		url :   '/ProductClass/update/' + $("#productClass_productClassId_edit").val(),
		type : "post",
		dataType: "json",
		data: new FormData($("#productClassEditForm")[0]),
		success : function (obj, response, status) {
            if(obj.success){
                alert("信息修改成功！");
                location.href= basePath + "ProductClass/frontlist";
            }else{
                alert(obj.message);
            } 
		},
		processData: false,
		contentType: false,
	});
}

$(function(){
	/*小屏幕导航点击关闭菜单*/
    $('.navbar-collapse a').click(function(){
        $('.navbar-collapse').collapse('hide');
    });
    new WOW().init();

})
</script>
</body>
</html>

PythonProject/templates/ProductClass/productClass_frontshow.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
  <TITLE>查看商品类别详情</TITLE>
  <link href="{% static 'plugins/bootstrap.css' %}" rel="stylesheet">
  <link href="{% static 'plugins/bootstrap-dashen.css' %}" rel="stylesheet">
  <link href="{% static 'plugins/font-awesome.css' %}" rel="stylesheet">
  <link href="{% static 'plugins/animate.css' %}" rel="stylesheet">
</head>
<body style="margin-top:70px;"> 
{% include 'header.html' %}
<div class="container">
	<ul class="breadcrumb">
  		<li><a href={% url 'Index:index' %}">首页</a></li>
  		<li><a href="{% url 'ProductClass:frontList' %}">商品类别信息</a></li>
  		<li class="active">详情查看</li>
	</ul>
	<div class="row bottom15"> 
		<div class="col-md-2 col-xs-4 text-right bold">商品类别编号:</div>
		<div class="col-md-10 col-xs-6">{{ productClass.productClassId }}</div>
	</div>
	<div class="row bottom15"> 
		<div class="col-md-2 col-xs-4 text-right bold">商品类别名称:</div>
		<div class="col-md-10 col-xs-6">{{ productClass.productClassName }}</div>
	</div>
	<div class="row bottom15">
		<div class="col-md-2 col-xs-4"></div>
		<div class="col-md-6 col-xs-6">
			<button onclick="history.back();" class="btn btn-primary">返回</button>
		</div>
	</div>
</div> 
{% include 'footer.html' %}
<script src="{% static 'plugins/jquery.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap.js' %}"></script>
<script src="{% static 'plugins/wow.min.js' %}"></script>
<script>
$(function(){
        /*小屏幕导航点击关闭菜单*/
        $('.navbar-collapse a').click(function(){
            $('.navbar-collapse').collapse('hide');
        });
        new WOW().init();
 })
 </script> 
</body>
</html>